### ISSUE TITLE
raster → terra

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#11]
Können wir auf `terra::rast()` umstellen?

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_n/3_Berechnung_Homeranges_Loesung.qmd#L134-L135

können wir das besser mit SpatialDataScience abgleichen?

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_n/3_Berechnung_Homeranges_Loesung.qmd#L160-L175

**Comment by ratnanil** [comment]
@BeniSigrist, kannst du schauen, ob meine neu Implementierung (mit `sf` und `terra`) deinen Vorstellungen entspricht? 

fallstudie_n/3_Berechnung_Homeranges_Uebung.qmd

**Comment by BeniSigrist** [comment]
Ja, passt super. Danke!
