### ISSUE TITLE
stat 1 - 4 + statkons 1- 4: Download Demoscript

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#17]
Hier werden die Demoscripts zum Download angeboten. Gibt es hier eine einfachere Lösung?

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/stat1-4/Statistik1_Demo.qmd#L14-L15

uvm.

**Comment by Hepi2** [comment]
Ich find's gut so.

**Comment by ratnanil** [comment]
ok super!
