### ISSUE TITLE
case_when statt verschachtelte if_else

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#19]
würde ich eher mit einem `case_when()` lösen

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_s/7_Multivariat_Loesung.qmd#L234-L244

**Comment by ratnanil** [comment]
siehe #18

**Comment by ratnanil** [comment]
see #34

**Comment by hochad** [comment]
@ratnanil, folgender Abschnitt in script 5_Datenverarbeitung funktioniert bei mir nicht:

`depo <- depo|>
  mutate(Tageszeit = case_when(
    Datetime >= nightEnd & Datetime <= goldenHourEnd ~ "Morgen",
    Datetime > goldenHourEnd & Datetime < goldenHour ~ "Tag",
    Datetime >= goldenHour & Datetime <= night       ~ "Abend",
    .default = "Nacht")) |>
    mutate(Tageszeit = factor(Tageszeit, levels = c("Morgen", "Tag", "Abend", "Nacht"),ordered = TRUE))`

Fehlermeldung:
```
Error in `mutate()`:
! Problem while computing `Tageszeit = case_when(...)`.
Caused by error in `case_when()`:
! Case 4 (`Datetime >= nightEnd & Datetime <= goldenHourEnd ~ "Morgen"`) must be a two-sided formula, not a character vector.
Run `rlang::last_error()` to see where the error occurred
```

**Comment by ratnanil** [comment]
Welche dplyr version hast du? Älter als 1.1.1?

**Comment by hochad** [comment]
ja, version 1.0.9. Ich habe ein Update durchgeführt und nun läuft es ohne probleme.
