### ISSUE TITLE
library(tidyverse) vermeiden

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#2]
https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_n/2_Datenverarbeitung_Loesung.qmd#L61-L62

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_s/2_Felderhebung.qmd#L59-L60

uvm

**Comment by ratnanil** [comment]
- [x] sigb
- [ ] hoce
- [ ] hepe

**Comment by ratnanil** [comment]
dies muss noch in Statistik (@Hepi2, @GAEgeler) und fallstudie-s (@hochad) umgesetzt werden.

**Comment by hochad** [comment]
in fallstudie-s umgesetzt

**Comment by BeniSigrist** [comment]
@ratnanil perfekt, merci!
