### ISSUE TITLE
separate mutate() und filter() Befehle vereinen

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#24]
https://github.com/ResearchMethods-ZHAW/HS23/blob/3904926f8419caf9088424befa92ad7ad083ed48/fallstudie_s/5_Vorverarbeitung_Loesung.qmd#L155-L157

https://github.com/ResearchMethods-ZHAW/HS23/blob/3904926f8419caf9088424befa92ad7ad083ed48/fallstudie_s/5_Vorverarbeitung_Loesung.qmd#L165-L169

diese Befehle könnte man vereinen

**Comment by ratnanil** [comment]
Adi kümmert sich drum

**Comment by hochad** [comment]
done
