### ISSUE TITLE
References

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#27]
-> Vorgehen analog Coppes et al.

**Comment by ratnanil** [comment]
-> Hirschparasitenbeispiel aus Kapitel 13 von Zuur et al. (2009)

**Comment by ratnanil** [comment]
@Hepi2 : um welches Paper handelt es sich hier: 

https://github.com/ResearchMethods-ZHAW/HS23/blob/47ff49b939786e8cff961d13dcf24dc0d81a3498/stat5-8/Statistik5_Demo.qmd#L51

**Comment by DLND8** [comment]
-> Wildi pp. 96 et seq.

**Comment by DLND8** [comment]
Logan fehlt auch

https://github.com/ResearchMethods-ZHAW/HS23/blob/a1c10b38e19e61c8ef0e1bb4ce0b7333a227dc22/stat1-4/Statistik3_Demo.qmd#L188

**Comment by Hepi2** [comment]
"Wildi (2017)" ist unterdessen bereits in der Referenzenliste

"Logan" ist dieses Buch:
Murray Logan
First published:16 April 2010
Biostatistical Design and Analysis Using R: A Practical Guide
Print ISBN:9781405190084 
Online ISBN:9781444319620
DOI:10.1002/9781444319620

"Zuur et al. (2009) ist dieses Buch.
Alain F. Zuur, Elena N. Ieno, Neil J. Walker, Anatoly A. Saveliev, and
Graham M. Smith.
2009
Mixed Effects Models and Extensions in Ecology with R
New York, NY: Springer,
ISBN: 978-0-387-87457-9.

Dank& Gruss
Dani
