### ISSUE TITLE
Datumsangaben

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#29]

**Comment by ratnanil** [comment]
@hochad, @BeniSigrist, könnt ihr die folgenden Daten noch anpassen?

https://github.com/ResearchMethods-ZHAW/HS23/blob/7fa5019ffd2b42981c226a3b8ffac9f9438eb7cd/fallstudie_s/2_Felderhebung.qmd#L27

https://github.com/ResearchMethods-ZHAW/HS23/blob/7fa5019ffd2b42981c226a3b8ffac9f9438eb7cd/fallstudie_s/3_Aufgabenstellung.qmd#L6


Tipp: Ich versuche solche Datumsangaben im Dokument zu vermeiden, und halte es eher generisch (z.B. "bis nächste Woche").

**Comment by hochad** [comment]
Danke für den Tipp @ratnanil. Ich habe das in meinen Scripts so umgesetzt.

**Comment by BeniSigrist** [comment]
betrifft das fallstudie_n auch? falls ja, wo?

**Comment by ratnanil** [comment]
> betrifft das fallstudie_n auch? falls ja, wo?

nein, bei dir habe ich keine Datumsangaben gefunden. Ich schliesse das Issue
