### ISSUE TITLE
Mit ipak alle packages für den jeweiligen Block installieren

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#3]
https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_n/3_Berechnung_Homeranges_Loesung.qmd#L15-L23

uvm

**Comment by ratnanil** [comment]
Nils setzt das für `fallstudie-biodiversity-n` um

**Comment by ratnanil** [comment]
@BeniSigrist: ich finde die `ipak` Funktion super, um jeweils für einen gesamten Block alle nötigen Packages zu installieren. Habe dies sowohl für die Fallstudie als auch für unsere Teile eingefügt. 

![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/d50d0801-183f-4290-9c2e-ed018a848714)

**Comment by ratnanil** [comment]
@BeniSigrist: Kannst du überprüfen, ob das für dich so passt?
@hochad, @Hepi2, @GAEgeler: Wollt ihr dieses Vorgehen für eure Teile auch machen? Ich kann das für dich auch erledigen, habe da einen Workflow.

**Comment by hochad** [comment]
@ratnanil : ich bin froh, wenn du das für fallstudie-s erledigen kannst (und mir erklären kannst, was diese Funktion so gut macht)

**Comment by ratnanil** [comment]
> ich bin froh, wenn du das für fallstudie-s erledigen kannst 

erledigt

> und mir erklären kannst, was diese Funktion so gut macht

Die Idee kommt von @BeniSigrist. Es geht darum, dass wir auf möglichst einfach Art dafür sorgen wollen, dass die Studis alle notwendigen Packages für den jeweiligen Block installiert haben. Gleichzeitig sollen aber bereits installierte Packages *nicht* installiert werden.

**Comment by hochad** [comment]
@ratnanil, in welchem file hast du das genau gemacht? sorry, ich kann gerade nicht nachvollziehen, wo die Änderung war.

**Comment by hochad** [comment]
danke! für mich ist dieses issue damit erledigt

**Comment by BeniSigrist** [comment]
@ratnanil perfekt, danke!
