### ISSUE TITLE
Unterschied zwischen Übung und Lösung

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#30]
Related to #20 

@BeniSigrist: Ist es korrekt, dass der Unterschied zwischen *Berechnung Homeranges - Übung* "Übung" und "Lösung" nur darin liegt, dass in den Lösungen die jeweiligen _Outputs_ der Codes angezeigt wird? Der Code selbst ist bereits in der Übung sichtbar?

Hier die Unterlagen vom letzten Jahr:

https://researchmethods-zhaw.github.io/HS22/fallstudie_n/3_Berechnung_Homeranges_Uebung.html
https://researchmethods-zhaw.github.io/HS22/fallstudie_n/3_Berechnung_Homeranges_Loesung.html

Das Gleiche scheint für Aufgaben 1 - 3 in *Variablenselektion Multivariate Modelle / Habitatselektionsmodell* zu gelten:

https://researchmethods-zhaw.github.io/HS22/fallstudie_n/5_Variablenselektion_Uebung.html
https://researchmethods-zhaw.github.io/HS22/fallstudie_n/5_Variablenselektion_Loesung.html

und auch für *Modellgüte und -diagnostics MM / Habitatselektionsmodell - Lösung*

https://researchmethods-zhaw.github.io/HS22/fallstudie_n/6_Guete_und_Diagnostics_Uebung.html
https://researchmethods-zhaw.github.io/HS22/fallstudie_n/6_Guete_und_Diagnostics_Loesung.html

Kannst du das mal anschauen, @BeniSigrist? Gerne können wir das auch in einem Meeting besprechen.

**Comment by BeniSigrist** [comment]
@ratnanil stimmt so nur für die Aufgaben in BiEc3_N, für BiEc5_N und BiEc6_N nur teilweise, sollten wir besprechen
