### ISSUE TITLE
datasets fehlen

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS23#37]
@ratnanil, die beiden .csv dateien, welche du für mich erstellt hast (ferien, lockdown), fehlen im Ordner datasets.
Kannst du sie bitte hochladen?

**Comment by ratnanil** [comment]
@hochad: Die daten habe ich eigentlich schon hochgeladen, zumindest sind sie auf github. Kannst du mal folgendes im Terminal eingeben?

```
cd datasets
git pull origin main
```

**Comment by hochad** [comment]
danke @ratnanil , mit den beiden zeilen code für das terminal hat es geklappt!
