### ISSUE TITLE
Package "dave" ist nicht mehr auf CRAN verfügbar

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/HS23#44]
Das Package "dave" wird in Stat 6, 7, 8 und Konsolidierung benötigt, ist aber nicht mehr auf CRAN verfügbar.

-> https://cran.r-project.org/web/packages/dave/index.html

```
Package ‘dave’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/dave).

Archived on 2023-05-08 as issues were not corrected in time.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-05-08_check_results_dave.html).

Please use the canonical form https://cran.r-project.org/package=dave to link to this page.
```

**Comment by DLND8** [comment]
Wir könnten eine kurze Anleitung schreiben, dass die Studenten das File aus dem Archive runterladen und manuell in RStudio hinzufügen.

**Comment by ratnanil** [comment]
ich würde dringenst davon abraten, packages zu verwenden, die nicht mehr auf CRAN sind. Brauchen wir das package wirklich?

**Comment by DLND8** [comment]
Commit https://github.com/ResearchMethods-ZHAW/HS23/commit/a8c1b4a46b542893b7851afeb7618a3a836dc136 beinhaltet: 

Die Daten sind jetzt als csv im datasets Repo abgespeichert. Die Library wird nicht mehr verwendet.
-   Datensatz *dave_sveg.csv*
-   Datensatz *dave_ssit.csv*

Alt:
```
library("dave")
```

Neu:
```
library("readr")
library("vegan")
sveg <- read_delim("datasets/stat5-8/dave_sveg.csv")
ssit <- read_delim("datasets/stat5-8/dave_ssit.csv")
```

@Hepi2 @GAEgeler Könntet ihr bitte kurz eure Statistik qmd's durchschauen ob soweit noch alles passt.
