### ISSUE TITLE
Action #73 fails

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS23#45]
@ratnanil  und @DLND8 : ich kann meine neusten Änderungen lokal zwar problemlos rendern und auch pushen: die Seite kann aber nicht neu "gebaut" werden.
Wisst ihr, woran das liegen könnte?

Hier könnte der Hinweis sein:
[https://github.com/ResearchMethods-ZHAW/HS23/actions/runs/6321493200/job/17165589212](https://github.com/ResearchMethods-ZHAW/HS23/actions/runs/6321493200/job/17165589212)

`[45/63] statKons/StatKons3_Demo_LM.qmd
WARNING: Error parsing /home/runner/work/HS23/HS23/statKons/StatKons3_Demo_LM_files/execute-results/html.json; it looks possibly like a git merge conflict.
Error in loadNamespace(x) : there is no package called ‘rmarkdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted`

LG
Adrian

**Comment by DLND8** [comment]
Ich habe nochmals alle Abschnitte gerendert und jetzt funktioniert es wieder https://github.com/ResearchMethods-ZHAW/HS23/commit/e60422c543df4046c8a8a2cebaa7d3be29bf9343. Gruss
