### ISSUE TITLE
freeze: true

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#49]
Hallo miteinander,

Mir ist erst jetzt aufgefallen, dass mit der Einstellung `freeze: true` der R-code nur beim allerersten Mal ausgeführt wird, danach nicht mehr. 

> `freeze: true`  # never re-render during project render

Um die execution zu forcieren, muss der Ordner oder Dateiname explizit erwähnt werden. Also z.B. (Möglichkeit 1)

```
quarto render prepro/Prepro1_Demo.qmd  # R-code in diesem Dokument wird ausgeführt
quarto render prepro                   # R-code aller Dokumente in diesem Ordner wird ausgeführt
```

Möglichkeit 2 wäre, `freeze` auf `auto` zu setzen. So wird der R-Code ausgeführt, sobald sich etwas im Dokument ändert. 

> `freeze: auto`  # re-render only when source changes

Möglichkeit 1 hat der Vorteil, dass nie code R-Code versehentlich ausgeführt wird. Der Nachteil ist, dass man immer daran denken muss, `quarto render` korrekt (also explizit) auszuführen. Welche Methode bevorzugt ihr, @hochad, @Hepi2, @BeniSigrist ?

**Comment by BeniSigrist** [comment]
freeze: true

**Comment by hochad** [comment]
meines Erachtens funktioniert in meinem Fall auch `quarto render "fallstudie_S`.
Wir können es also so belassen, wie bis anhin.

**Comment by DLND8** [comment]
@ratnanil Kann dieser Issue geschlossen werden?
