### ISSUE TITLE
mytheme

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#5]
Thematisch müssten wir das in infovis einführen. Ist das nötig? Reicht `theme_classic()` nicht?

https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/stat1-4/Statistik1_Demo.qmd#L101-L106

uvm.

**Comment by Hepi2** [comment]
Jürgen möchte das als Wiederholung drin lassen, weil es wichtig ist für publikationswürdige Plots.
