### ISSUE TITLE
Merge conflicts in freeze-files

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#50]
Schon lange sind mir merge conflicts in Dateien im `_freeze` Ordner ein Dort im Auge. Diese merge conflicts verursachen Arbeit, obwohl sie nicht behoben werden müssen (es handelt sich ja schliesslich ledliglich um output / target-Files). Ich habe deshalb dem Repo eine neue Datei namens `.gitattributes` hinzugefügt, mit folgendem Inhalt:

```
_freeze/* merge=ours
```

Dies soll bewirken, dass bei allen Files im Ordner `_freeze` bei merge conflicts die jeweils eigene (`ours`) gegenüber der incoming (`theirs`) Version gültig ist. 

Dies einfach als FYI. Ich hoffe, es funktioniert so jetzt besser.

**Comment by DLND8** [comment]
@ratnanil Kann dieser Issue geschlossen werden?

**Comment by ratnanil** [comment]
ja, aber vorher im readme noch erwähnen
