### ISSUE TITLE
"there is no package called 'agricolae'" obwohl es da ist

### ISSUE THREAD

**Issue by Hepi2** [ResearchMethods-ZHAW/HS23#52]
In Stat2
https://researchmethods-zhaw.github.io/HS23/stat1-4/Statistik2_Demo.html
Auf der Homepage steht der Ouutput
"## Error in library("agricolae"): there is no package called 'agricolae'" obwohl das Packet eigentlich vorhanden sein sollte.
Allenfalls kann Dominic mir bei der Behebung dieses Problems am Montagmorgen helfen?

**Comment by DLND8** [comment]
Problem gelöst
