### ISSUE TITLE
Hier.part nicht mehr auf Cran, Alternative nicht installierbar

### ISSUE THREAD

**Issue by Hepi2** [ResearchMethods-ZHAW/HS23#54]
Stefan schrieb:
"Package Hier.part nicht mehr auf Cran
Ein guter, mächtigerer Ersatz ist das Package realimpro
Siehe https://doi.org/10.18637/jss.v017.i01 für weitere Infos und Methodenvergleich zu Hier.part"

Das Problem ist nun dass man realimpro nicht installieren kann. Obschon es glaub auf Cran ist.

**Comment by DLND8** [comment]
https://github.com/ResearchMethods-ZHAW/HS23/blob/1a2b1c176a056e873b57cda984a83c07102ee722/stat1-4/Statistik3_Demo.qmd#L264

https://github.com/ResearchMethods-ZHAW/HS23/blob/1a2b1c176a056e873b57cda984a83c07102ee722/statKons/StatKons3_Demo_LM.qmd#L337

**Comment by DLND8** [comment]
Statistik3 wurde von @Hepi2 angepasst. https://github.com/ResearchMethods-ZHAW/HS23/commit/114ab9bd3eab611a53e5e98b1dc096b234a945b5 

@GAEgeler kannst du diese neue Logik auch bei StatKons ergänzen?

**Comment by Hepi2** [comment]
Im Demo 3 habe ich den Code entsprechend angepasst und Dominic hat das relaimpo-Package in die Packages bei den Vorbereitungen eingetragen. Ich vermute, dass die Methode bei StatKons (Hierarchische Partitionierung) bei StatKons nicht angewandt wird.  Oder @GAEgeler? Falls dem so ist, kannst das Issue schliessen. LGD

**Comment by DLND8** [comment]
Doch, es wird in StatKons3 verwendet. Siehe hier:

https://github.com/ResearchMethods-ZHAW/HS23/blob/1a2b1c176a056e873b57cda984a83c07102ee722/statKons/StatKons3_Demo_LM.qmd#L337

**Comment by Hepi2** [comment]
@GAEgeler 
Kannst du dich um den Ersatz von Hier.Part in StatKons3 kümmern?
Hier der "Ersatzcode" (von Stefan Widmer) den ich bereits in Stat3 Demo eingefügt habe:
library(relaimpo)
lm_1 <- lm(ABUND~YR.ISOL+ AREA +  DIST + LDIST + GRAZE + ALT, data = loyn)
metrics <- calc.relimp(lm_1, type = c("lmg", "first", "last","betasq", "pratt"))
IJ <- cbind(I = metrics$lmg, J = metrics$first - metrics$lmg, Total = metrics$first) 
IJ

**Comment by GAEgeler** [comment]
Done, danke für den Hinweis.
