### ISSUE TITLE
Execute error = False

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/HS23#55]
Momentan haben wir im yml `execute: error = true` gesetzt. Dies führt aber dazu, dass das rendern immer funktioniert und Fehler im R Code ignoriert werden.

```
execute:
  freeze: true
  **error: true**
```

Zu Beginn, als wir das Ganze auf Quarto umgebaut haben, hat das noch Sinn gemacht, doch nun führt es zu ungewollten Fehler auf der Webseite, welche oft nicht sofort gesehen werden.

Daher finde ich wir sollten diese global auf `false `stellen.

@Hepi2 @ratnanil @GAEgeler @hochad @BeniSigrist: Was meint ihr dazu?

**Comment by hochad** [comment]
ok für mich

**Comment by GAEgeler** [comment]
für mich auch passend, habe ich es richtig verstanden, dass du es nun global angepasst hast, d.h. auf den einzelnen files muss man nichts mehr anpassen oder?

**Comment by DLND8** [comment]
Ja das wird global gemacht, Ich habe es jetzt mal mit dem commit https://github.com/ResearchMethods-ZHAW/HS23/commit/0b988f09600fce5035db7c2ca40de27895e2f998 aktiviert. Schauen wir mal ob es so besser funktioniert

**Comment by Hepi2** [comment]
OK. Scheint zu funktionieren. Issue schliessen?
