### ISSUE TITLE
File not found: dave_sveg.csv, important for Demo 6

### ISSUE THREAD

**Issue by GAEgeler** [ResearchMethods-ZHAW/HS23#56]
Hoi Dani

Kurze Frage: im Daten-Ordner Statistik finde ich leider die folgende Datei nicht "dave_sveg.csv". Für die Demo morgen bräuchte ich diese noch - sofern noch möglich, wäre ich dir dankbar, wenn du es mir noch schicken oder hochladen könntest!

Grazcha fich

**Comment by ratnanil** [comment]
Hey Dani, der Datensatz ist hier: https://github.com/ResearchMethods-ZHAW/datasets/tree/main/stat5-8

Du kannst in deinem HS23 Repo folgendes machen:

```
cd datasets
git pull origin main
cd ..
```

**Comment by GAEgeler** [comment]
@ratnanil frage, bis vor kurzem hatte ich noch eine andere datenstrukur beim ordner datasets, habt ihr da mal was verändert?

**Comment by GAEgeler** [comment]
> Hey Dani, der Datensatz ist hier: https://github.com/ResearchMethods-ZHAW/datasets/tree/main/stat5-8
> 
> Du kannst in deinem HS23 Repo folgendes machen:
> 
> ```
> cd datasets
> git pull origin main
> cd ..
> ```

Danke Nils, das passt so für mich! @Hepi2 du brauchts nichts mehr zu unternehmen!
