### ISSUE TITLE
Übergang r-chunk zu markdown

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#6]
https://github.com/ResearchMethods-ZHAW/HS23/blob/5b9d7ae5324c852604123666a6bbf46b914f26b0/fallstudie_n/2_Datenverarbeitung_Loesung.qmd#L33-L40

![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/6c475af5-3596-42d0-8f5c-ecf59752c7e2)

ist das wirklich so gedacht?

**Comment by ratnanil** [comment]
@BeniSigrist: habe ich das richtig angepasst?

Vorher (HS22):

![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/d8a44a20-a031-4d82-a846-f860817adfba)


Nachher (HS23):

![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/d9059f11-b00a-4519-a097-4a8d029cd209)

**Comment by BeniSigrist** [comment]
@ratnanil das passt, besten Dank!
