### ISSUE TITLE
Nummerierung vereinheitlichen?

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#8]
Kriegen wir eine einheitliche nummerierung hin?

| Prepro/Infovis/Rauman  | Fallstudie S                  | Fallstudie N | 
|-------------|----------------------------|-------|
| ![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/94d6ebf4-f09c-415b-a52b-6bf02d7bc8b0)        | ![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/240278b1-973f-436c-97e8-5755286aa5c0) | ![image](https://github.com/ResearchMethods-ZHAW/HS23/assets/12532091/dd12aa2f-3039-4802-bf22-a1386eb7708c)

**Comment by ratnanil** [comment]
Nils und Beni überlegen sich sinnvolle Nummerierungen:

- Kurze Namen sind besser
- Nummerierung hilft die entsprechende Woche zu erkennen.

**Comment by ratnanil** [comment]
@BeniSigrist und @hochad: was haltet ihr von:

- BiEc1 - Vorbemerkung
- BiEc1 - Übung
- `---------------------`
- BiEc2 - Übung
- BiEc3 - Übung
- usw.

Also Präfix BiEc, dann die Nummer jeweiligen Einheit, danach eine kurze Beschreibng wie "Übung", Vorbemerkung" o.ä?

**Comment by hochad** [comment]
einverstanden mit einer kleinen ergänzung:

- BiEc**S**1 - Vorbemerkung

**Comment by BeniSigrist** [comment]
Ich habs folgendermassen umgesetzt:
BiEc1_N Vorbermerkung
BiEc2_N Daten(vor)verarbeitung
BiEc3_N Homeranges
BiEc4_N Multivariate Modelle
usw....

**Comment by ratnanil** [comment]
Super!
