### ISSUE TITLE
CSV's importieren

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#9]
Können wir uns auf einen Importbefehl einigen? Aktuell haben wir:

- read.csv
- read.delim
- read_csv
- read_delim
- uvm.

Ich habe immer für `readr` Funktionen plädiert, v.a. weil:

- `stringasfactors = FALSE`
- Datetime tz ist UTC
- tibbles werden in der Konsole übersichtlicher dargestellt

**Comment by hochad** [comment]
Für meinen Teil ist dies umgesetzt.

**Comment by BeniSigrist** [comment]
@ratnanil passt für mich sehr gut

**Comment by ratnanil** [comment]
update warning here: 

https://researchmethods-zhaw.github.io/HS23/prepro/Prepro1_Uebung.html#aufgabe-4

> Wenn du read_csv verwenden möchtest: Diese Funktion erwartet leicht andere inputs als read.csv, konsultiere dazu die Hilfe zu read_csv (mit ?read_csv).

**Comment by Hepi2** [comment]
OK, auch ich mag read_delim.
@ratnanil gibt es einen Weg, um gleich in mehren qmd-files nach "read" zu suchen, oder muss man alle einzeln überprüfen?

**Comment by ratnanil** [comment]
>  @ratnanil gibt es einen Weg, um gleich in mehren qmd-files nach "read" zu suchen, oder muss man alle einzeln überprüfen?

Ja! Mit der Tastenkombinaiton <kbd>Ctrl</kbd>+ <kbd>Shift</kbd>+ <kbd>F</kbd>

**Comment by DLND8** [comment]
Angepasst für stat1-4 und stat5-8.

https://github.com/ResearchMethods-ZHAW/HS23/commit/051922bdd6bff0468cb6be7bd13a178cc27aaa9d

Schliesse den Issue da nur noch read_delim und read_csv verwendet werden.
